---
- name: Make sure MariaDB is installed (Debian)
  ansible.builtin.apt:
    name: "{{ itop_mysql_apt_packages }}"
    update_cache: true
    cache_valid_time: 3600
    state: present
  when: ansible_os_family == 'Debian'

- name: Make sure MariaDB is installed (Red Hat)
  ansible.builtin.yum:
    name: "{{ itop_mysql_yum_packages }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Start MariaDB (Red Hat)
  ansible.builtin.systemd:
    name: mariadb
    state: started
    enabled: true
#  when: ansible_os_family == 'RedHat'

- name: Create iTop database
  community.mysql.mysql_db:
    name: "{{ itop_mysql_db_name }}"
    state: present
    login_unix_socket: "{{ itop_mysql_control_socket }}"

- name: Create itop user in MariaDB
  community.mysql.mysql_user:
    name: "{{ itop_mysql_user }}"
    password: "{{ itop_mysql_password }}"
    priv: "{{ itop_mysql_db_name }}.*:ALL"
    state: present
    login_unix_socket: "{{ itop_mysql_control_socket }}"
  no_log: true
