---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: debian-13
    image: docker.io/geerlingguy/docker-debian13-ansible
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    exposed_ports:
      - 80/tcp
    published_ports:
      - 0.0.0.0:8888:80/tcp
  - name: ubuntu-24
    image: docker.io/geerlingguy/docker-ubuntu2404-ansible
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    exposed_ports:
      - 80/tcp
    published_ports:
      - 0.0.0.0:8889:80/tcp
  - name: rocky-8
    image: docker.io/rockylinux:8
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    exposed_ports:
      - 80/tcp
    published_ports:
      - 0.0.0.0:8890:80/tcp
provisioner:
  name: ansible
  inventory:
    host_vars:
      centos-8:
        itop_fastcgi_socket: "php-fpm"
        itop_preseed_url: "http://localhost:8890/"
      debian-buster:
        itop_fastcgi_socket: "unix:/var/run/php/php7.3-fpm.sock"
        itop_preseed_url: "http://localhost:8888/"
      ubuntu-20:
        itop_fastcgi_socket: "unix:/var/run/php/php7.4-fpm.sock"
        itop_preseed_url: "http://localhost:8889/"
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
